### ISSUE TITLE
Extracting the z matrix

### ISSUE THREAD

**Issue by drnickisaac** [drnickisaac/sMon-Amphibia#1]
Try this on a model that has converged
`update(out, parameters="z", n.iter=100)`

**Comment by bowlerbear** [comment]
Closing this issues as we have now run the model using JAGS directly (using the sparta BUGS code) and then the update function to extract z.
 A rough graph is:
![spatialpattern](https://user-images.githubusercontent.com/9789903/37900944-3b763a10-30df-11e8-8655-947a41eb4a6f.png)
